-- Implement NOT NULL, UNIQUE, DEFAULT, and CHECK constraints.

CREATE TABLE IF NOT EXISTS constraint_demo(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 username text NOT NULL UNIQUE, age integer CHECK(age>=17),
 city text DEFAULT 'Chennai'
);
