-- Create tables using Supabase.

CREATE TABLE IF NOT EXISTS public.students (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text UNIQUE NOT NULL,
  age integer CHECK (age >= 17),
  department text DEFAULT 'CSE',
  created_at timestamptz DEFAULT now()
);
