-- Define columns and PostgreSQL data types.

CREATE TABLE IF NOT EXISTS public.data_types_demo(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text, age integer, fee numeric(10,2), active boolean,
 dob date, created_at timestamptz DEFAULT now(), metadata jsonb
);
