-- Implement primary keys and foreign keys.

CREATE TABLE IF NOT EXISTS departments(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name text NOT NULL);
CREATE TABLE IF NOT EXISTS employees(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name text,dept_id bigint REFERENCES departments(id));
